# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/Chicago"
    open-pull-requests-limit: 8

  # Authentication backend
  - package-ecosystem: "npm"
    directory: "/cilogon"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "openid-client"
        versions: ["6.x.x"]  # Ignore openid-client v6 due to major module changes
