services:
  app:
    image: iguide-ue-frontend-${VITE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  auth:
    image: iguide-ue-auth-${VITE_ENV}
    build:
      context: ./cilogon/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8443:8443"
    restart: always