services:
  app:
    image: iguide-ux-dev-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  auth:
    image: iguide-ux-dev-auth
    build:
      context: ./cilogon/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8443:8443"
    restart: always