version: '0.1'

services:
  app:
    image: data-with-notebooks:v0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf