services:
  app:
    image: iguide-ux-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  auth:
    image: iguide-ux-dev-auth
    build:
      context: ./cilogon/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    