services:
  app:
    image: iguide-ue-frontend-${VITE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  auth:
    image: iguide-ue-auth-${VITE_ENV}
    volumes:
      - ./cilogon/logs:/app/logs
    build:
      context: ./cilogon/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8443:8443"
    restart: always

  prerender:
    image: iguide-ue-prerender-${VITE_ENV}
    build:
      context: ./server/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9222:9222"
